### ISSUE TITLE
Translation - readme.stacktical.com

### ISSUE THREAD

**Issue by darrylhansen** [Stacktical/stacktical-dsla-residency#3]
## The Issue

To support DSLA Protocol's internationalization effort, we require the content of the [Stacktical Readme](https://readme.stacktical.com/) site translated into various other languages.

---

# Git Issue format

### About DSLA protocol

DSLA Protocol is a smart-contract based application and network middleware for managing risk. It allows developers to plug risk management capabilities into their applications and uses incentives to align the goals of different stakeholders.

### **Prize Bounty**

The prize bounty for this task is 50000 DSLA.

### **Challenge Description**

Translate the content of the [Stacktical readme](https://readme.stacktical.com) into an alternate language to support our internationalization effort.

Potential languages include:

- Spanish
- French
- Chinese
- Russian
- Arabic
- German
- Indonesian
- Portuguese

### How to participate?

**Step 1: Pick a task**

Browse Github issues and raise your hand 🙋‍♂️ in the comments section to show interest.

**Step 2: Contact us**

Email [founders+residency@stacktical.com](mailto:founders+residency@stacktical.com) with:

Your Github username

An introduction about yourself

A link to the task of your choice

An outline of your plan to complete it

Include some prior similar works as a reference, if applicable

**Step 3: Onboarding**

If you are selected for the task, the core team will allocate resources to facilitate its completion.

Some tasks might require signing a Non Disclosure Agreement (NDA).

**Step 4: Complete your task**

Some marketing or content related tasks may require review and updates before being accepted.

Congratulations on contributing to DSLA! 🎉

Completed tasks will be reflected in this repository.

### **Judging Criteria**

1. Quality: Overall quality of submission.

### **Follow DSLA Protocol**

**DSLA Residency Github** [https://github.com/Stacktical/stacktical-dsla-residency](https://github.com/Stacktical/stacktical-dsla-residency)
**DSLA DTK Github** [https://github.com/Stacktical/stacktical-dsla-developer-toolkit](https://github.com/Stacktical/stacktical-dsla-developer-toolkit)
**DSLA Protocol Developer Guide** [https://readme.stacktical.com/developer-guide/](https://readme.stacktical.com/developer-guide/)
**DSLA Protocol Discord (for technical discussions)** [https://discord.gg/bknuhcXV](https://discord.gg/bknuhcXV)
**DSLA Support Telegram** [https://t.me/dsla_network](https://t.me/dsla_network)
**DSLA Protocol Community Telegram** [https://t.me/stacktical](https://t.me/stacktical)

**Comment by itsthalisman** [comment]
I would like to translate your readme page into Brazilian Portuguese if there is still a vacancy for this language pair.

**Comment by darrylhansen** [comment]
> 

Good afternoon! We are just in the process of finalizing how these issues will be managed and awarded. Keep an eye on this space for updates soon and then we will get our Residency tasks rolling.

**Comment by itsthalisman** [comment]
That is great to hear, Darryl. Thank you so much for your response. I just sent an email to the residency founders' email account  about this particular task. 

Would you advise me to join DSLA's Discord server or their Telegram in order to keep myself updated about the Residency tasks?

**Comment by darrylhansen** [comment]
> That is great to hear, Darryl. Thank you so much for your response. I just sent an email to the residency founders' email account about this particular task.
> 
> Would you advise me to join DSLA's Discord server or their Telegram in order to keep myself updated about the Residency tasks?

The Discord will be more Developer focused, so I would say for this join the Telegram, follow on Twitter and keep an eye on our blog as well: blog.stacktical.com 😄

**Comment by itsthalisman** [comment]
I'll keep an eye out for any updates then. Thank you so much.

**Comment by StassijnsSam** [comment]
I am wondering if Dutch is a language you are interested in?

**Comment by darrylhansen** [comment]
Hi @PH03N1X101, for now we are focused on the eight languages noted, but thank you for your inquiry!

We will be rolling out a new method for managing Residency tasks soon though, so encourage you to keep an eye out 😄

**Comment by darrylhansen** [comment]
@itsthalisman @PH03N1X101, we are transitioning the Residency Challenges to [Dework](https://dework.xyz/dsla). Should have bounties setup in the near future, so please keep an eye on it and once that's ready we can begin assigning tasks through Dework.

Please join our [Guild](https://guild.xyz/dsla) to get a DSLA Community Discord role (free, quick and easy), which is integrated with Dework as well!
